add_moduledirs("modules")
includes("compiler")
includes("rules")
includes("plugins")

namespace("xmcu", function()
    add_rules("xmcu.common")
    includes("vendor")
    includes("third-party")
    target("deps")
        set_kind("object")
        add_deps("vendor", {public=true})
    target_end()
end)
