#ifndef __HEATSHRINK_KCONFIG_H__
#define __HEATSHRINK_KCONFIG_H__

#ifdef HEATSHRINK_CONFIG_H
#include <xhive_config.h>

#ifdef CONFIG_HEATSHRINK_DYNAMIC_ALLOC
#define HEATSHRINK_DYNAMIC_ALLOC 1
#else
#define HEATSHRINK_DYNAMIC_ALLOC 0
#endif

#ifdef CONFIG_HEATSHRINK_STATIC_INPUT_BUFFER_SIZE
#define HEATSHRINK_STATIC_INPUT_BUFFER_SIZE CONFIG_HEATSHRINK_STATIC_INPUT_BUFFER_SIZE
#else
#define HEATSHRINK_STATIC_INPUT_BUFFER_SIZE 32
#endif

#ifdef CONFIG_HEATSHRINK_STATIC_WINDOWS_BITS
#define HEATSHRINK_STATIC_WINDOWS_BITS CONFIG_HEATSHRINK_STATIC_WINDOWS_BITS
#else
#define HEATSHRINK_STATIC_WINDOWS_BITS 8
#endif

#ifdef CONFIG_HEATSHRINK_STATIC_LOOKAHEAD_BITS
#define HEATSHRINK_STATIC_LOOKAHEAD_BITS CONFIG_HEATSHRINK_STATIC_LOOKAHEAD_BITS
#else
#define HEATSHRINK_STATIC_LOOKAHEAD_BITS 4
#endif

#endif /* HEATSHRINK_CONFIG_H */
#endif /* __HEATSHRINK_KCONFIG_H__ */
